// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/engineervix/pseudoc",
        "contact": {
            "name": "Pseudoc Support",
            "url": "https://github.com/engineervix/pseudoc/issues"
        },
        "license": {
            "name": "BSD-3-Clause",
            "url": "https://github.com/engineervix/pseudoc/blob/main/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate": {
            "post": {
                "description": "Generate a document using JSON request body. Provides more flexibility than GET endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Generate document via POST request",
                "parameters": [
                    {
                        "description": "Document generation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Generated document file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or parameters",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/generate/{type}": {
            "get": {
                "description": "Generate a document using URL path parameter and query parameters. Supports PDF, DOCX, XLSX, and random document types.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Generate document via GET request",
                "parameters": [
                    {
                        "enum": [
                            "pdf",
                            "docx",
                            "xlsx",
                            "random"
                        ],
                        "type": "string",
                        "example": "pdf",
                        "description": "Document type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 3,
                        "example": 5,
                        "description": "Number of pages (PDF/DOCX only)",
                        "name": "pages",
                        "in": "query"
                    },
                    {
                        "maximum": 10,
                        "minimum": 1,
                        "type": "integer",
                        "default": 2,
                        "example": 3,
                        "description": "Number of sheets (XLSX only)",
                        "name": "sheets",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "example": 42,
                        "description": "Random seed for reproducible generation",
                        "name": "seed",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "my-document",
                        "description": "Custom filename (without extension)",
                        "name": "filename",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Generated document file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the current health status of the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Server is healthy",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Server is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Returns detailed information about the server including supported formats, limits, and runtime info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get server information",
                "responses": {
                    "200": {
                        "description": "Server information",
                        "schema": {
                            "$ref": "#/definitions/internal_server_handlers.InfoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_server_handlers.CheckResult": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "\"ok\", \"warning\", \"error\"",
                    "type": "string"
                }
            }
        },
        "internal_server_handlers.ErrorResponse": {
            "description": "Standard error response format",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string",
                    "example": "Invalid document type"
                },
                "message": {
                    "type": "string",
                    "example": "Supported types: pdf, docx, xlsx, random"
                },
                "request_id": {
                    "type": "string",
                    "example": "req_123456789"
                },
                "validation_errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_server_handlers.ValidationError"
                    }
                }
            }
        },
        "internal_server_handlers.GenerateRequest": {
            "description": "Request body for document generation via POST",
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "filename": {
                    "type": "string",
                    "example": "my-document"
                },
                "pages": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1,
                    "example": 5
                },
                "seed": {
                    "type": "integer",
                    "example": 42
                },
                "sheets": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1,
                    "example": 3
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "pdf",
                        "docx",
                        "xlsx",
                        "random"
                    ],
                    "example": "pdf"
                }
            }
        },
        "internal_server_handlers.HealthResponse": {
            "description": "Server health status information",
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_server_handlers.CheckResult"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "system": {
                    "$ref": "#/definitions/internal_server_handlers.SystemInfo"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "uptime": {
                    "type": "string",
                    "example": "2h30m15s"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "internal_server_handlers.InfoResponse": {
            "description": "Comprehensive server information and capabilities",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Lorem Ipsum for Documents"
                },
                "endpoints": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "limits": {
                    "$ref": "#/definitions/internal_server_handlers.Limits"
                },
                "name": {
                    "type": "string",
                    "example": "pseudoc"
                },
                "server_info": {
                    "$ref": "#/definitions/internal_server_handlers.ServerInfo"
                },
                "supported_formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "pdf",
                        "docx",
                        "xlsx"
                    ]
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "internal_server_handlers.Limits": {
            "type": "object",
            "properties": {
                "max_file_size_bytes": {
                    "type": "integer"
                },
                "max_pages": {
                    "type": "integer"
                },
                "max_sheets": {
                    "type": "integer"
                },
                "rate_limit_per_minute": {
                    "type": "integer"
                },
                "request_timeout": {
                    "$ref": "#/definitions/time.Duration"
                }
            }
        },
        "internal_server_handlers.ServerInfo": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "internal_server_handlers.SystemInfo": {
            "type": "object",
            "properties": {
                "goroutine_count": {
                    "type": "integer"
                },
                "memory_usage_mb": {
                    "type": "integer"
                }
            }
        },
        "internal_server_handlers.ValidationError": {
            "description": "Detailed validation error information",
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "pages"
                },
                "message": {
                    "type": "string",
                    "example": "pages must be between 1 and 100"
                },
                "value": {
                    "type": "string",
                    "example": "150"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        }
    },
    "tags": [
        {
            "description": "Document generation endpoints for PDF, DOCX, XLSX, and random document types",
            "name": "documents"
        },
        {
            "description": "Health check and server information endpoints",
            "name": "health"
        },
        {
            "description": "Server information and capabilities",
            "name": "info"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0-alpha.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Pseudoc API",
	Description:      "Lorem Ipsum for Documents - Generate placeholder documents for testing and development workflows",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
